[project]
name = "opendebat"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "dlt[duckdb]>=1.20.0",
    "enlighten>=1.14.1",
    "pydantic>=2.12.5",
    "typer>=0.21.0",
    "xmltodict>=1.0.2",
]
